clean:
	make -f Makefile_355 clean --no-print-directory
	make -f Makefile_421 clean --no-print-directory
	make -f Makefile_430 clean --no-print-directory
	make -f Makefile_431 clean --no-print-directory
	make -f Makefile_440 clean --no-print-directory
	make -f Makefile_441 clean --no-print-directory
	make -f Makefile_446 clean --no-print-directory
	make -f Makefile_450 clean --no-print-directory
	make -f Makefile_453 clean --no-print-directory
	make -f Makefile_455 clean --no-print-directory
	make -f Makefile_460 clean --no-print-directory
	make -f Makefile_465 clean --no-print-directory
	make -f Makefile_466 clean --no-print-directory
	make -f Makefile_470 clean --no-print-directory
all:
	make -f Makefile_355 clean --no-print-directory
	make -f Makefile_355 --no-print-directory
	make -f Makefile_421 clean --no-print-directory
	make -f Makefile_421 --no-print-directory
	make -f Makefile_430 clean --no-print-directory
	make -f Makefile_430 --no-print-directory
	make -f Makefile_431 clean --no-print-directory
	make -f Makefile_431 --no-print-directory
	make -f Makefile_440 clean --no-print-directory
	make -f Makefile_440 --no-print-directory
	make -f Makefile_441 clean --no-print-directory
	make -f Makefile_441 --no-print-directory
	make -f Makefile_446 clean --no-print-directory
	make -f Makefile_446 --no-print-directory
	make -f Makefile_450 clean --no-print-directory
	make -f Makefile_450 --no-print-directory
	make -f Makefile_453 clean --no-print-directory
	make -f Makefile_453 --no-print-directory
	make -f Makefile_455 clean --no-print-directory
	make -f Makefile_455 --no-print-directory
	make -f Makefile_460 clean --no-print-directory
	make -f Makefile_460 --no-print-directory
	make -f Makefile_465 clean --no-print-directory
	make -f Makefile_465 --no-print-directory
	make -f Makefile_466 clean --no-print-directory
	make -f Makefile_466 --no-print-directory
	make -f Makefile_470 clean --no-print-directory
	make -f Makefile_470 --no-print-directory
